name: Traduzir NBA

# dispara a cada 5 minutos
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install python-docx requests python-dotenv

      - name: Executar script de tradução
        env:
          IMAP_HOST: ${{ secrets.IMAP_HOST }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          DESTINO: ${{ secrets.DESTINO }}
        run: |
          python traduzir_email.py
